name: 'Deploy Chart'
description: 'Deploy Chart'
inputs:
  KUBECTL_CONFIG:
    description: ""
    required: true
  VALUES_FILE_NAME:
    description: ""
    required: true
  URL_FILESHARE:
    description: ""
    required: true
  USERNAME_FILESHARE:
    description: ""
    required: true
  RSA-KEY_FILESHARE:
    description: ""
    required: true
  CHART_REPO:
    description: ""
    required: true
  DEPLOYMENT_NAME:
    description: "Name of the Helm deployment."
    required: true
  DEPLOYMENT_NAMESPACE:
    description: ""
    default: "default"
  GITHUB_TOKEN:
    description: ""
    required: true

runs:
  using: "composite"
  steps:

    - name: Clear WorkingDirectory
      shell: bash
      run: rm -r ./*

    # Download Secure-File
    - name: base64-to-file Kube
      id: write_file
      uses: timheuer/base64-to-file@v1.1
      with:
        fileName: "custom-config"
        encodedString: ${{ inputs.KUBECTL_CONFIG }}

    - name: base64-to-file ID
      id: write_id_file
      uses: timheuer/base64-to-file@v1.1
      with:
        fileName: "id_rsa"
        encodedString: ${{ inputs.RSA-KEY_FILESHARE }}

    - name: Set Key Protections
      shell: bash
      run: chmod 600 ${{ steps.write_id_file.outputs.filePath }}

    - name: Get Values File
      shell: bash
      run: |
        scp -P 23 -i ${{ steps.write_id_file.outputs.filePath }} -o "StrictHostKeyChecking no" ${{ inputs.USERNAME_FILESHARE }}@${{ inputs.URL_FILESHARE }}:${{ inputs.VALUES_FILE_NAME }} ./Values.yml

    - name: Git Clone Action
      shell: bash
      run: git clone https://${{ inputs.GITHUB_TOKEN }}@${{ inputs.CHART_REPO }} ./Chart

    # Deploy to Kubernetes
    - name: Helm Upgrade
      shell: bash
      run: helm upgrade -i ${{ inputs.DEPLOYMENT_NAME}} ./Chart --values ./Values.yml --kubeconfig ${{ steps.write_file.outputs.filePath }} -n ${{ inputs.DEPLOYMENT_NAMESPACE }}